// End Points for Auth
const baseUrl = 'https://backend.betterway-egypt.com/api/client/';

/// profile end points
const registerEndPoint = 'register';
const loginEndPoint = 'login';
const homeEndPoint = 'home';
const categoriesEndPoint = 'categories';
const subCategoriesEndPoint = 'subcategories';
const brandsEndPoint = 'brands';
const brandsProductsEndPoint = 'brands/products';
const buyBrandOfferEndPoint = 'brands/products/buy';
const reviewEndPoint = 'brands/review/add';
const logoutEndPoint = 'logout';
const referralsEndPoint = 'wallet/transfer/check';
const planProductsEndPoint = 'plan/products';
const buyPlanProductsEndPoint = 'plan/products/buy';
const nationalitiesEndPoint = 'nationalities';
const countriesEndPoint = 'countries';
const completeProfileEndPoint = 'profile/complete';
const profileEndPoint = 'profile';
const updateProfileEndPoint = 'profile/update';
const networkEndPoint = 'network';
const networkPointsPersonsEndPoint = 'network/stats';
const networkReferralTableEndPoint = 'network/table/referral';
const networkTableEndPoint = 'network/table';
const friendsEndPoint = 'friend/list';
const acceptFriendRequestEndPoint = 'friend/status';
const addFriendRequestEndPoint = 'friend/add';
const walletSearchPerson = 'wallet/transfer/check';
const walletTransferRequest = 'wallet/transfer';
const walletTransferHistoryRequest = 'wallet/transfer/history';
const walletLedger = 'wallet/ledger';
const walletVerifyPaymentRequest = 'wallet/transfer/verify';
const toolsEndPoint = 'tool';
const eventsEndPoint = 'event';
const buyToolsEndPoint = 'tool/buy';
const buyEventsEndPoint = 'event/pay';
const upgradePlanProductEndPoint = 'plan/products/upgrade';
const buyUpgradePlanProductEndPoint = 'plan/products/upgrade/buy';
const brandProductsHistory = 'brands/products/history';
const walletRewardPointsEndPoint = 'wallet/points';
const chequeEndPoint = 'wallet/cheque';
const activationEndPoint = 'plan/products/history';
const changeSecurityCodeEndPoint = 'securitycode/change';
const editAgenciesEndPoint = 'plan/network/agencies/edit';
const getAgenciesEndPoint = 'plan/network/agencies';
const chatListEndPoint = 'chat';
const chatDetailsEndPoint = 'chat/details';
const sendMessageEndPoint = 'chat/send';
const brandRequestEndPoint = 'brands/contactus';

String citiesEndPoint(countryId) => 'cities/$countryId';
String friendProfileEndPoint(profileId) => 'friend/profile/$profileId';
String toolDetailsEndPoint(toolId) => 'tool/details/$toolId';
String eventDetailsEndPoint(eventId) => 'event/details/$eventId';

String areasEndPoint(cityId) => 'areas/$cityId';
